name: Deploy-SNAPSHOT

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: yarn install
      - name: Update your package.json with an npm pre-release version
        id: pre-release-version
        uses: adobe/update-prerelease-npm-version@v1.0.0
        with:
          pre-release-tag: 'snapshot' 
          package-name: "package-snapshot"
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
