name: Deploy-SNAPSHOT

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    permissions:
      contents: write
      pull-requests: read
      packages: write
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./github/workflows/build.yml
      - name: Update your package.json with an npm pre-release version
        id: pre-release-version
        uses: adobe/update-prerelease-npm-version@v1.1.0
        with:
          pre-release-tag: 'snapshot' 
          skip-dependencies-to-update: true
      - run: yarn publish --tag SNAPSHOT
        env:
          NODE_AUTH_TOKEN : ${{ secrets.ACTIONS_PAT }}
