name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_PAT }}
      - run: yarn build
      - run: yarn publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_PAT }}
